package com.tincore.gsp.server.domain;

import java.util.Date;

import javax.persistence.Column;

public interface Constants {
    Date DATE_DATA_ITEM_RESYNC = new Date(1);
    
	double UNKNOWN_DOUBLE = Double.MIN_VALUE;
	double SPEED_UNKNOWN = UNKNOWN_DOUBLE;
	double GRADE_UNKNOWN = UNKNOWN_DOUBLE;
	double ALTITUDE_UNKNOWN = UNKNOWN_DOUBLE;
	double LOCATION_UNKNOWN = UNKNOWN_DOUBLE;
	double BEARING_UNKNOWN = UNKNOWN_DOUBLE;
	double POWER_UNKNOWN = UNKNOWN_DOUBLE;
	double TILT_UNKNOWN = UNKNOWN_DOUBLE;
	int UNKNOWN_INT = Integer.MIN_VALUE;
	double CADENCE_UNKNOWN = UNKNOWN_DOUBLE;
	int LUX_UNKNOWN = -1;
	double CALORIES_UNKNOWN = -1;

	int ACTIVITY_LEVEL_UNKNOWN = -1;
	int ACTIVITY_LEVEL_SLEEP_MIN = 0;
	int ACTIVITY_LEVEL_SLEEP_DEEP = 50;
	int ACTIVITY_LEVEL_SLEEP = 100;

	int ACTIVITY_LEVEL_SEDENTARY_DEEP = 150;
	int ACTIVITY_LEVEL_SEDENTARY = 200;
	int ACTIVITY_LEVEL_SEDENTARY_MIN = ACTIVITY_LEVEL_SLEEP;

	int ACTIVITY_LEVEL_ACTIVE = 300;
	int ACTIVITY_LEVEL_ACTIVE_MIN = ACTIVITY_LEVEL_SEDENTARY;

//	String UUID_TYPE = "UUID"; // "BINARY(16)"; was problematic with liquibase
	String UUID_TYPE = "BINARY(16)"; 
}